### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by AdrianM10** [MicrosoftDocs/data-api-builder-docs#1]
## Issue: Dead Links

The links for [Authentication](https://github.com/Azure/data-api-builder/blob/main/docs/authentication.md) and [Authorization](https://github.com/Azure/data-api-builder/blob/main/docs/authorization.md) under [Next Steps](https://learn.microsoft.com/en-us/azure/data-api-builder/overview-to-data-api-builder#next-steps) point to pages that don't exist and return a 404 error.

**Comment by seantleonard** [comment]
Hi @AdrianM10 drianM10, Thanks for reporting, I'll get those fixed.

**Comment by seesharprun** [comment]
These are not fixed!

**Comment by seantleonard** [comment]
> These are not fixed!

Have recent updates broken these?

**Comment by seesharprun** [comment]
I think they are fixed now. I just double-checked and they are working.

#please-close
