### ISSUE TITLE
Does PK required on the table for DAB? ASML Customer getting PK error with DAB CLI

### ISSUE THREAD

**Issue by HitenBhavsarMSFT** [MicrosoftDocs/data-api-builder-docs#13]
SR 2401020050002991, 

does DAB CLI required PK on the table? ASML customers have heap table and its was failing with below error, once we added PK all working fine. 

![image](https://github.com/MicrosoftDocs/data-api-builder-docs/assets/72768193/6e259a7b-ab53-4b25-98f8-8e1e9b6014da)

If PK is must, please add on the public facing documentation for all the RDBMS. If not then why are we getting this error?

**Comment by seesharprun** [comment]
This has been added the public documentation. Thanks for the feedback!

**Comment by seesharprun** [comment]
#please-close

**Comment by seesharprun** [comment]
#please-close
