### ISSUE TITLE
Incorrect Numbers of parameters + Bug

### ISSUE THREAD

**Issue by albertoRamon** [MicrosoftDocs/data-api-builder-docs#8]
On “[Views and Stored Procedures](https://learn.microsoft.com/en-us/azure/data-api-builder/views-and-stored-procedures)”: 
![image](https://github.com/MicrosoftDocs/data-api-builder-docs/assets/15262462/68868431-dc49-4434-9d64-683119d8ed49)

The command on [SP](https://learn.microsoft.com/en-us/azure/data-api-builder/views-and-stored-procedures#stored-procedures) is missing the second parameter
![image](https://github.com/MicrosoftDocs/data-api-builder-docs/assets/15262462/ce022bea-7481-440a-8a42-10cda91dd68d)

`Invalid request. Missing required procedure parameters: author, searchType for entity: GetCowrittenBooksByAuthor`

The correct command must be:  But Fail for a CLI Issue v0.8.51 ??:

```
dab add GetCowrittenBooksByAuthor `
   --source dbo.stp_get_all_cowritten_books_by_author `
   --source.type "stored-procedure" source.params "searchType:s,author:Issac Assimov" `
   --permissions "anonymous:execute" `
   --rest.methods "get" `
   --graphql.operation "query"
```

If you edit the JSON manually works fine:
```JSON
      "source": {
        "object": "dbo.stp_get_all_cowritten_books_by_author",
        "type": "stored-procedure",
        "parameters": {
          "searchType": "s",
           "author": "Isaac Asimov"
        }
      }
```

**Comment by seesharprun** [comment]
This was fixed in the latest version of the documentation. Thanks for the feedback!

**Comment by seesharprun** [comment]
#please-close

**Comment by albertoRamon** [comment]
Thank for everything
