### ISSUE TITLE
"Quickstart: Use Data API builder with Azure Cosmos DB" doesn't provide sample data

### ISSUE THREAD

**Issue by jacksorjacksor** [MicrosoftDocs/data-api-builder-docs#9]
Hi there!

While the tutorial [Quickstart: Use Data API builder with Azure Cosmos DB](https://github.com/MicrosoftDocs/data-api-builder-docs/blob/main/data-api-builder/get-started/get-started-azure-cosmos-db.md#quickstart-use-data-api-builder-with-azure-cosmos-db) says "We'll use the [embedded data model](https://github.com/MicrosoftDocs/data-api-builder-docs/blob/main/azure/cosmos-db/nosql/modeling-data#embedding-data) in this sample." this article does not provide any references to the `books` or `authors` data which is then used in the article, or the file source of `books` as use in the [Add Book entity](https://github.com/MicrosoftDocs/data-api-builder-docs/blob/main/data-api-builder/get-started/get-started-azure-cosmos-db.md#add-book-entity) section.

I believe the data being referenced is [here](https://github.com/Azure/data-api-builder/blob/main/samples/getting-started/azure-cosmos-db/books.json) but I do not believe that is referenced in the tutorial itself.

Please could you let me know if I've misunderstood or could you please include references to where the sample data should be found please?

TIA!

Rich

**Comment by seesharprun** [comment]
The new Quickstart now provides sample data. Thanks for the feedback!

**Comment by jacksorjacksor** [comment]
Great, thank you!
